#!/usr/bin/env python3
"""
Firmware Version Manager
HUSKY-SORTER-001

Tracks ESP32 firmware versions, manages changelog, and coordinates
firmware deployments across multiple devices.

Usage:
    python firmware_version_manager.py --log              # Show version history
    python firmware_version_manager.py --current 1.0.0   # Set current version
    python firmware_version_manager.py --release 1.0.1    # Create release entry
    python firmware_version_manager.py --compare 1.0.0 1.0.1  # Compare versions

Firmware Version Schema: MAJOR.MINOR.PATCH (e.g., 1.2.3)
- MAJOR: Breaking changes (architecture/API overhaul)
- MINOR: New features, backward compatible
- PATCH: Bug fixes, backward compatible
"""

import argparse
import json
import os
import sys
from datetime import datetime, timedelta
from typing import Optional
from dataclasses import dataclass, asdict


VERSION_FILE = "firmware_version.json"
CHANGELOG_FILE = "firmware_changelog.md"


@dataclass
class FirmwareVersion:
    version: str
    major: int
    minor: int
    patch: int
    build_date: str
    build_timestamp: int
    board: str = "esp32wroom"
    flash_size: str = "4MB"
    partition: str = "app0"
    notes: str = ""
    changelog: list = None
    
    def __post_init__(self):
        if self.changelog is None:
            self.changelog = []
    
    def to_dict(self) -> dict:
        d = asdict(self)
        return d
    
    @classmethod
    def from_dict(cls, d: dict) -> 'FirmwareVersion':
        d.pop('version', None)  # Remove computed field
        return cls(version=f"{d['major']}.{d['minor']}.{d['patch']}", **d)
    
    def __str__(self):
        return f"v{self.major}.{self.minor}.{self.patch}"
    
    def __lt__(self, other: 'FirmwareVersion'):
        return (self.major, self.minor, self.patch) < (other.major, other.minor, other.patch)
    
    def __eq__(self, other: 'FirmwareVersion'):
        return (self.major, self.minor, self.patch) == (other.major, other.minor, other.patch)


def parse_version(v: str) -> FirmwareVersion:
    """Parse version string into FirmwareVersion object."""
    try:
        parts = v.split('.')
        if len(parts) != 3:
            raise ValueError(f"Invalid version format: {v}")
        major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2])
        now = datetime.now()
        return FirmwareVersion(
            version=v,
            major=major, minor=minor, patch=patch,
            build_date=now.strftime("%Y-%m-%d"),
            build_timestamp=int(now.timestamp())
        )
    except Exception as e:
        raise ValueError(f"Cannot parse version '{v}': {e}")


def load_version_history() -> dict:
    """Load version history from JSON file."""
    if os.path.exists(VERSION_FILE):
        with open(VERSION_FILE, 'r') as f:
            return json.load(f)
    return {"versions": [], "current": None, "devices": {}}


def save_version_history(data: dict) -> None:
    """Save version history to JSON file."""
    with open(VERSION_FILE, 'w') as f:
        json.dump(data, f, indent=2)


def generate_changelog_md(versions: list) -> str:
    """Generate markdown changelog from version list."""
    lines = [
        "# Firmware Changelog — HUSKY-SORTER-001",
        "",
        "> Auto-generated by firmware_version_manager.py",
        "",
        "## Format",
        "",
        "```",
        "## vMAJOR.MINOR.PATCH — YYYY-MM-DD",
        "",
        "### Changes",
        "- [FEAT] New feature description",
        "- [FIX] Bug fix description",
        "- [BREAK] Breaking change (requires re-flash)",
        "- [SEC] Security update",
        "```",
        "",
        "---",
        "",
    ]
    
    for v in sorted(versions, key=lambda x: (x['major'], x['minor'], x['patch']), reverse=True):
        date = v.get('build_date', 'TBD')
        lines.append(f"## v{v['major']}.{v['minor']}.{v['patch']} — {date}")
        lines.append("")
        
        notes = v.get('notes', '')
        if notes:
            lines.append(f"**Notes:** {notes}")
            lines.append("")
        
        changelog = v.get('changelog', [])
        if changelog:
            lines.append("### Changes")
            for entry in changelog:
                tag = entry.get('tag', 'MISC')
                desc = entry.get('desc', '')
                lines.append(f"- [{tag}] {desc}")
            lines.append("")
        
        lines.append("---")
        lines.append("")
    
    return "\n".join(lines)


def show_version_log(history: dict) -> None:
    """Display version history."""
    print("\n📋 Firmware Version History")
    print("=" * 60)
    
    versions = history.get('versions', [])
    if not versions:
        print("   No versions logged yet.")
        print(f"   Run: python firmware_version_manager.py --release X.Y.Z")
        return
    
    current = history.get('current', 'none')
    print(f"   Current version: {current}")
    print()
    print(f"   {'Version':<12} {'Date':<12} {'Board':<15} {'Notes'}")
    print(f"   {'-'*10:<12} {'-'*10:<12} {'-'*13:<15} {'-'*30}")
    
    for v in sorted(versions, key=lambda x: (x['major'], x['minor'], x['patch']), reverse=True):
        ver = f"v{v['major']}.{v['minor']}.{v['patch']}"
        date = v.get('build_date', 'TBD')
        board = v.get('board', 'esp32wroom')
        notes = v.get('notes', '')[:35]
        marker = " ← current" if ver == current else ""
        print(f"   {ver:<12} {date:<12} {board:<15} {notes}{marker}")
    
    # Show device tracking
    devices = history.get('devices', {})
    if devices:
        print()
        print("📱 Device Firmware Status")
        print("-" * 40)
        for dev_id, info in devices.items():
            dv = info.get('firmware_version', 'unknown')
            last_seen = info.get('last_seen', 'never')
            print(f"   {dev_id:<20} {dv:<12} {last_seen}")
    
    print()


def compare_versions(v1: str, v2: str) -> None:
    """Compare two firmware versions."""
    ver1 = parse_version(v1)
    ver2 = parse_version(v2)
    
    print("\n🔍 Version Comparison")
    print("=" * 60)
    print(f"   Version A: {ver1}")
    print(f"   Version B: {ver2}")
    print()
    
    if ver1 == ver2:
        print("   ⚖️  Both versions are identical")
    elif ver1 < ver2:
        print(f"   ⬆️  {ver2} is NEWER than {ver1}")
        print(f"   📈 Upgrade path: {ver1} → {ver2}")
        diff = (ver2.major - ver1.major, ver2.minor - ver1.minor, ver2.patch - ver1.patch)
        changes = []
        if diff[0] > 0: changes.append(f"MAJOR: {diff[0]} breaking change(s)")
        if diff[1] > 0: changes.append(f"MINOR: {diff[1]} new feature(s)")
        if diff[2] > 0: changes.append(f"PATCH: {diff[2]} bug fix(es)")
        for c in changes:
            print(f"      • {c}")
    else:
        print(f"   ⬇️  {ver1} is NEWER than {ver2}")
        print(f"   📉 Downgrade path: {ver1} → {ver2}")
    
    # Check compatibility
    print()
    if ver1.major != ver2.major:
        print("   ⚠️  MAJOR version difference — possible API incompatibility!")
        print("      Consider full re-flash and configuration reset.")
    elif ver1.minor != ver2.minor:
        print("   ✅ MINOR version difference — backward compatible")
        print("      Safe to upgrade, but review release notes.")
    else:
        print("   ✅ PATCH version difference — fully backward compatible")
        print("      Safe to upgrade anytime.")


def release_version(version: str, notes: str = "", changelog: list = None) -> None:
    """Create a new firmware version release."""
    ver = parse_version(version)
    history = load_version_history()
    
    # Check for duplicates
    existing = [v for v in history['versions'] 
                if v['major'] == ver.major and v['minor'] == ver.minor and v['patch'] == ver.patch]
    if existing:
        print(f"❌ Version {ver} already exists! Use bump instead or increment patch.")
        return
    
    # Add to history
    ver_data = ver.to_dict()
    if changelog:
        ver_data['changelog'] = changelog
    if notes:
        ver_data['notes'] = notes
    
    history['versions'].append(ver_data)
    history['current'] = str(ver)
    
    save_version_history(history)
    
    # Update changelog markdown
    changelog_md = generate_changelog_md(history['versions'])
    with open(CHANGELOG_FILE, 'w') as f:
        f.write(changelog_md)
    
    print(f"✅ Version {ver} released!")
    print(f"   Date: {ver.build_date}")
    print(f"   Timestamp: {ver.build_timestamp}")
    if notes:
        print(f"   Notes: {notes}")
    if changelog:
        print(f"   Changelog entries: {len(changelog)}")
    print(f"\n   Files updated:")
    print(f"   • {VERSION_FILE}")
    print(f"   • {CHANGELOG_FILE}")


def bump_version(part: str = "patch") -> None:
    """Bump current version (patch/minor/major)."""
    history = load_version_history()
    current = history.get('current')
    
    if not current:
        print("❌ No current version set. Use --release to create first version.")
        return
    
    ver = parse_version(current)
    
    if part == "major":
        new_ver = f"{ver.major + 1}.0.0"
    elif part == "minor":
        new_ver = f"{ver.major}.{ver.minor + 1}.0"
    else:
        new_ver = f"{ver.major}.{ver.minor}.{ver.patch + 1}"
    
    print(f"📈 Bumping {part}: {current} → {new_ver}")
    release_version(new_ver)


def register_device(device_id: str, version: str = None, port: str = None) -> None:
    """Register a device with its firmware version."""
    history = load_version_history()
    
    current = history.get('current') if not version else version
    
    if 'devices' not in history:
        history['devices'] = {}
    
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    history['devices'][device_id] = {
        'firmware_version': current or 'unknown',
        'port': port or '',
        'last_seen': now,
        'registered': now
    }
    
    save_version_history(history)
    print(f"✅ Device {device_id} registered with firmware {current}")


def check_update_available(device_id: str) -> None:
    """Check if device firmware is outdated."""
    history = load_version_history()
    current = history.get('current')
    
    device = history.get('devices', {}).get(device_id)
    if not device:
        print(f"❌ Device {device_id} not registered. Run: --register {device_id}")
        return
    
    device_ver = device.get('firmware_version', 'unknown')
    
    if not current:
        print("❌ No current version in version history.")
        return
    
    if device_ver == current:
        print(f"✅ Device {device_id} is up-to-date: {device_ver}")
    else:
        print(f"🔄 Device {device_id} can be updated:")
        print(f"   Current on device: {device_ver}")
        print(f"   Latest available:  {current}")
        print(f"   Run: firmware_update_tool.py --bin <new_firmware.bin> --port {device.get('port', '/dev/ttyUSB0')}")


def main():
    parser = argparse.ArgumentParser(
        description='Firmware Version Manager — HUSKY-SORTER-001',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  View version history:
    python firmware_version_manager.py --log

  Release new version:
    python firmware_version_manager.py --release 1.0.1 --notes "Fix HX711 stability"

  Bump patch version:
    python firmware_version_manager.py --bump

  Compare two versions:
    python firmware_version_manager.py --compare 1.0.0 1.1.0

  Register device:
    python firmware_version_manager.py --register sorter-pi-01 --port /dev/ttyUSB0

  Check for updates:
    python firmware_version_manager.py --check-update sorter-pi-01

Tips:
  - Always release with changelog entries for traceability
  - MAJOR bump = breaking changes (API/schematic overhaul)
  - MINOR bump = new features (backward compatible)
  - PATCH bump = bug fixes (fully backward compatible)
        """
    )
    
    parser.add_argument('--log', '-l', action='store_true',
                        help='Show version history')
    parser.add_argument('--release', '-r', metavar='X.Y.Z',
                        help='Release new version (e.g., 1.0.1)')
    parser.add_argument('--bump', '-b', choices=['patch', 'minor', 'major'], default='patch',
                        help='Bump current version (default: patch)')
    parser.add_argument('--compare', nargs=2, metavar=('V1', 'V2'),
                        help='Compare two versions')
    parser.add_argument('--register', metavar='DEVICE_ID',
                        help='Register device with current firmware')
    parser.add_argument('--check-update', metavar='DEVICE_ID',
                        help='Check if device needs update')
    parser.add_argument('--notes', default='',
                        help='Release notes (use quotes)')
    parser.add_argument('--port',
                        help='Device port (for registration)')
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("  Firmware Version Manager — HUSKY-SORTER-001")
    print("=" * 60)
    
    if args.log:
        history = load_version_history()
        show_version_log(history)
        return
    
    if args.compare:
        v1, v2 = args.compare
        compare_versions(v1, v2)
        return
    
    if args.release:
        changelog = []
        if sys.stdin.isatty():
            print("\n📝 Enter changelog entries (one per line, empty to finish):")
            while True:
                try:
                    line = input("   > ").strip()
                    if not line:
                        break
                    # Parse tag from [TAG] format
                    if line.startswith('['):
                        parts = line[1:].split(']', 1)
                        tag = parts[0] if parts else 'MISC'
                        desc = parts[1].strip() if len(parts) > 1 else ''
                    else:
                        tag = 'MISC'
                        desc = line
                    changelog.append({'tag': tag, 'desc': desc})
                except EOFError:
                    break
        else:
            # Non-interactive: parse from args or empty
            pass
        
        release_version(args.release, args.notes, changelog if changelog else None)
        return
    
    if args.bump:
        bump_version(args.bump)
        return
    
    if args.register:
        register_device(args.register, port=args.port)
        return
    
    if args.check_update:
        check_update_available(args.check_update)
        return
    
    # No action - show log
    history = load_version_history()
    show_version_log(history)
    print("Run --help for usage information.")


if __name__ == '__main__':
    main()